spring.application.name=spring-simple-store-v1

spring.datasource.url=jdbc:postgresql://localhost:5050/simple_store_v1
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

security.users.admin.username=admin
security.users.admin.password=admin123
security.users.client.username=client
security.users.client.password=client123
